Fix compilation errors
- AstVisitorEventSourceTests.cs(21,35): error CS0104:
  'List<>' is an ambiguous reference between 'Esprima.Ast.List<T>' and
  'System.Collections.Generic.List<T>'

- AstVisitorEventSourceTests.cs(27,29): error CS1503:
  Argument 2: cannot convert from 'method group' to 'int'

Fixes compilation broken since "Fix AstVisitor bugs that miss a few
nodes" (ccc2253e0fe074b146090b0399ed0047962c2abb).